version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - shop_postgre:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Mypassword
      - POSTGRES_USER=apicha_user
      - POSTGRES_DB=qrcode_order
    

  shop_backend:
    build: ./backend/
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - PictureData:/backend/app/Picture
volumes:
   shop_postgre:
    driver: local
   PictureData:
    driver: local
    